name: 'Shift Left Action'

on:
  push:
    branches:
    - master


jobs:
  build: 
#Set up environment
    runs-on: ubuntu-latest
    env:
      working-directory: . 
      CHKP_CLOUDGUARD_ID: ${{ secrets.CHKP_CLOUDGUARD_ID }}
      CHKP_CLOUDGUARD_SECRET: ${{ secrets.CHKP_CLOUDGUARD_SECRET }}
    steps:
 
#Pull Code   
    - name: Checkout Code
      uses: actions/checkout@v2
     
#Scan Web Application Code    
    - name: ShiftLeft SourceGuard Web Application Scan
      run: |
         wget https://shiftleft-prod.s3.amazonaws.com/blades/shiftleft/bin/linux/amd64/0.0.24/shiftleft
         chmod +x ./shiftleft
         ./shiftleft code-scan -s .
      continue-on-error: true
      
     #Build Container 
    - name: Build Docker Container
      run: |
         docker build . -t vulnado
    #Scan Container     
    - name: Shift Left Container Scan
      run: |
        docker save vulnado -o vulnado.tar
        ./shiftleft image-scan -t 1800 -i ./vulnado.tar
      continue-on-error: true         
